feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
app:
  stockServiceUrl: http://localhost:8080

server:
  port: 8081
  servlet:
    context-path: /api/order

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MARCINDB
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    jpa:
      repositories:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html